/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("de.maxhenkel.voicechat:voicechat-api:2.1.12")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
